### ISSUE TITLE
論文に記述する実験環境について

### ISSUE THREAD

**Issue by temochiz-lab** [temochiz-lab/common-2022#7]
メールから引用です。

- - -

それから実験環境の記述には、ブラウザはGooglechrome　で実施、と記述する必要があると思いますが、ヴァージョンも必要でしょうか？
他に、ソフトウェア環境として他に記述すべき事はありますか？
JSpsycho　Ver.7は書きます。

**Comment by temochiz-lab** [comment]
PCを使った実験での通例的なものとかありましたら合わせた方が良さそうですが、
実験環境はソフトウェア、ハードウェア両方ともあった方が同じ事をやりたい人に親切ですね。

表示する際の刺激の大きさや、呈示時間が短い場合だと機器によって差が出る可能性も考えると、
ハードウェアのスペックが欲しい気が。

渡辺先生、ご意見いかがでしょうか？

--------------------------
例)

動作環境
OS: Windows11
ブラウザ: Google Chorme 10x.x.xxxx
使用フレームワーク: jsPsych Ver7.xx

動作装置
PC: NEC xxxx (Core i5-1135G7 ・256GB SSD・8GBメモリ)
モニタ: (32インチ、1920x1024、60Hz)
--------------------------

**Comment by WATANABEMe** [comment]
お返事ありがとうございます。
今年度、実験室用の、デスクトップPCを購入しましたので、スペックが変わりますね。
今週納品になりました。
ゲーミングモニターも購入できるのですが、品薄で、納品が二ヶ月くらい先になってしまうかもしれません。

**Comment by temochiz-lab** [comment]
認識合いましたのでチケットクローズします。
